name: Deploy

on:
  push:
    branches:
    - master
    paths:
      - 'web/**'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Testando binário
      uses: actions/setup-node@v2-beta
      run: npm run testes

    - name: Publicando NPM
      uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      
    - name: Deploy no servidor
      uses: matheusvanzan/sshpass-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USUARIO }}
        password: ${{ secrets.SENHA }}
        run: |
          cd public_html/egua
          git pull

    - name: Funcionamento de pacote
      uses: actions/setup-node@v2-beta
      run: |
        npm i -g egua
        egua tests/tests.egua