name: Deploy

on:
  push:
    branches: [ master ]
    paths: [ 'web/**', 'package.json']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta

    - name: Testando binário
      run: npm run testes

    