name: Deploy - Hostgator

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Remote command
      uses: matheusvanzan/sshpass-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USUARIO }}
        password: ${{ secrets.SENHA }}
        run: |
          cd public_html/egua
          git pull
