name: Commit e PR - Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_master:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Teste binário
      run: npm run test
